name: Deploy to Firebase Hosting

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check for package-lock.json
      run: |
        if [ ! -f "package-lock.json" ]; then
          echo "package-lock.json not found, creating one..."
          npm install --package-lock-only
        fi
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-20-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-20-
          ${{ runner.os }}-node-
        
    - name: Install dependencies
      run: |
        if [ ! -d "node_modules" ]; then
          npm ci --prefer-offline --no-audit
        else
          echo "Dependencies already cached"
        fi
      
    - name: Build application for static hosting
      run: |
        # Remove API routes for static export
        echo "Removing API routes for static export..."
        rm -rf app/api
        
        # Enable static export for Firebase hosting deployment
        if grep -q '\/\/.*output.*export' next.config.ts 2>/dev/null; then
          echo "Enabling static export configuration for Firebase deployment..."
          sed -i 's/\/\/.*output.*export.*/output: "export",/g' next.config.ts
        elif ! grep -q 'output.*export' next.config.ts 2>/dev/null; then
          echo "Adding static export configuration..."
          sed -i '/trailingSlash: true,/a\  output: "export",' next.config.ts
        fi
        
        echo "Building Next.js application for static hosting..."
        npm run build
      env:
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
        NEXT_PUBLIC_API_FOOTBALL_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_FOOTBALL_BASE_URL }}
        NEXT_PUBLIC_API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        NEXT_PUBLIC_STATIC_BUILD: 'true'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Verify Firebase token
      run: |
        if [ -z "$FIREBASE_TOKEN" ]; then
          echo "❌ FIREBASE_TOKEN secret is not set!"
          echo "Please set the FIREBASE_TOKEN secret in your repository settings."
          echo "To generate a token, run: firebase login:ci"
          exit 1
        else
          echo "✅ Firebase token is available"
          echo "Token length: ${#FIREBASE_TOKEN}"
        fi
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Verify Firebase project
      run: |
        if [ -f "firebase.json" ]; then
          echo "✅ firebase.json found"
          cat firebase.json
        else
          echo "❌ firebase.json not found!"
          exit 1
        fi
        
    - name: Firebase login with token
      run: |
        echo "Authenticating with Firebase..."
        firebase login:ci --token "$FIREBASE_TOKEN"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Deploy to Firebase
      run: |
        echo "Deploying to Firebase Hosting..."
        firebase deploy --only hosting --token "$FIREBASE_TOKEN" --non-interactive
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
